apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: ruoyi-auth
  name: ruoyi-auth

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-auth
  template:
    metadata:
      labels:
        app: ruoyi-auth
    spec:
      subdomain: ruoyi-auth #配置内部网络DNS，可以访问node ip
      containers:
        - image: 192.168.0.107:5000/ruoyi-auth:latest
          name: ruoyi-auth
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service

metadata:
  labels:
    app: ruoyi-auth
  name: ruoyi-auth

spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ruoyi-auth