version: '3.8'
services:
  mysql-server:
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: mysql-server
    image: mysql:5.7
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
      - 3306:3306
